// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPtnK-dS2B7ejyNg06U6473yYpxUUQzmg',
    appId: '1:275139886228:web:e1338cfff551de68340881',
    messagingSenderId: '275139886228',
    projectId: 'tip-locker',
    authDomain: 'tip-locker.firebaseapp.com',
    storageBucket: 'tip-locker.firebasestorage.app',
    measurementId: 'G-NZWJ5WEF3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCILxkhQC7bmKDnlKUMdE1ZWKr72w4qSJk',
    appId: '1:275139886228:android:57bbf5ef28353839340881',
    messagingSenderId: '275139886228',
    projectId: 'tip-locker',
    storageBucket: 'tip-locker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOIDDnSFFyQ0QXTvyFolLE4S_AVc-8zN0',
    appId: '1:275139886228:ios:9d4682ef8b1d7b79340881',
    messagingSenderId: '275139886228',
    projectId: 'tip-locker',
    storageBucket: 'tip-locker.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOIDDnSFFyQ0QXTvyFolLE4S_AVc-8zN0',
    appId: '1:275139886228:ios:9d4682ef8b1d7b79340881',
    messagingSenderId: '275139886228',
    projectId: 'tip-locker',
    storageBucket: 'tip-locker.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPtnK-dS2B7ejyNg06U6473yYpxUUQzmg',
    appId: '1:275139886228:web:495e3bec822e6822340881',
    messagingSenderId: '275139886228',
    projectId: 'tip-locker',
    authDomain: 'tip-locker.firebaseapp.com',
    storageBucket: 'tip-locker.firebasestorage.app',
    measurementId: 'G-8SS7PLWDYR',
  );
}
